### ISSUE TITLE
FID50k Metric Troubles

### ISSUE THREAD

**Issue by ruslanvasylev** [skyflynil/stylegan2#21]
Hi there,

Does anyone know why FID50k metric errors out?
When I set my --metrics=None, everything works fine(the network trains and generates pkls and images), but when I default to FID50k, I get this:

`Traceback (most recent call last):
  File "run_training.py", line 223, in <module>
    main()
  File "run_training.py", line 218, in main
    run(**vars(args))
  File "run_training.py", line 140, in run
    dnnlib.submit_run(**kwargs)
  File "./dnnlib/submission/submit.py", line 343, in submit_run
    return farm.submit(submit_config, host_run_dir)
  File "./dnnlib/submission/internal/local.py", line 22, in submit
    return run_wrapper(submit_config)
  File "./dnnlib/submission/submit.py", line 280, in run_wrapper
    run_func_obj(**submit_config.run_func_kwargs)
  File "./training/training_loop.py", line 377, in training_loop
    metrics.run(pkl, run_dir=dnnlib.make_run_dir_path(), data_dir=dnnlib.convert_path(data_dir), num_gpus=num_gpus, tf_config=tf_config)
  File "./metrics/metric_base.py", line 151, in run
    metric.run(*args, **kwargs)
  File "./metrics/metric_base.py", line 62, in run
    self._reset(network_pkl=network_pkl, run_dir=run_dir, data_dir=data_dir, dataset_args=dataset_args, mirror_augment=mirror_augment)
  File "./metrics/metric_base.py", line 39, in _reset
    self._dataset_obj.close()
AttributeError: 'TFRecordDataset' object has no attribute 'close'`

Any pointers?

Thanks in advance.

**Comment by ruslanvasylev** [comment]
lol

dataset.py is missing the following:

`class TFRecordDataset:
    def close(self):
        pass`
